description: 'ResNet ImageNet'
output_dir: $SCRATCH/sc18-dl-tutorial/imagenet-cnn

data:
    name: imagenet
    train_dir: /global/cscratch1/sd/sfarrell/ImageNet-100/train
    valid_dir: /global/cscratch1/sd/sfarrell/ImageNet-100/validation

model:
    name: cnn
    input_shape: [224, 224, 3]
    n_classes: 100
    dropout: 0.2

optimizer:
    name: Adam
    lr: 0.0001

training:
    batch_size: 32
    n_epochs: 16
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy, top_k_categorical_accuracy]
