description: 'ResNet ImageNet'
output_dir: $SCRATCH/sc18-dl-tutorial/tinyimagenet-resnet

data:
    name: tiny-imagenet
    train_dir: /global/cscratch1/sd/sfarrell/tiny-imagenet/train
    valid_dir: /global/cscratch1/sd/sfarrell/tiny-imagenet/valid

model:
    name: resnet18_cifar
    input_shape: [64, 64, 3]
    n_classes: 200
    dropout: 0.5

optimizer:
    name: Adam
    lr: 0.0001

training:
    batch_size: 32
    n_epochs: 16
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy, top_k_categorical_accuracy]
